export const employeeList = [
  {
    id: 1,
    name: "Angela Moss",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "angelamoss@mail.com",
    image: "./images/pic_1.svg",
    initials: "AM",
  },
  {
    id: 2,
    name: "Ahmad Zayn",
    position: "Photographer at Audio Video Teams",
    mobile: "+12 345 6789 0",
    email: "ahmadzayn@mail.com",
    image: "./images/pic_2.svg",
    initials: "AZ",
  },
  {
    id: 3,
    name: "Brian Connor",
    position: "Designer at Crimson Guards Studios",
    mobile: "+12 345 6789 0",
    email: "brianconnor@mail.com",
    image: "./images/pic_3.svg",
    initials: "BC",
  },
  {
    id: 4,
    name: "Courtney Hawkins",
    position: "Programmer at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "courtneyhawk@mail.com",
    image: "./images/pic_4.svg",
    initials: "CH",
  },
  {
    id: 5,
    name: "Chyntia Smilee",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "angelamoss@mail.com",
    image: "./images/pic_5.svg",
    initials: "CS",
  },
  {
    id: 6,
    name: "David Here",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "davidhere@mail.com",
    image: "./images/pic_6.svg",
    initials: "DH",
  },
  {
    id: 7,
    name: "Dennise Lee",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "denniselee@mail.com",
    image: "./images/pic_7.svg",
    initials: "DL",
  },
  {
    id: 8,
    name: "Erbatov Axie",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "erbatovaxie@mail.com",
    image: "./images/pic_8.svg",
    initials: "EA",
  },
  {
    id: 9,
    name: "Evan Khan",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "angelamoss@mail.com",
    image: "./images/pic_9.svg",
    initials: "EK",
  },
  {
    id: 10,
    name: "Fanny Humble",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "fannyhumble@mail.com",
    image: "./images/pic_10.svg",
    initials: "FH",
  },
  {
    id: 11,
    name: "Franklin Jr.",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "franklinjr@mail.com",
    image: "./images/pic_11.svg",
    initials: "FJ",
  },
  {
    id: 12,
    name: "Gandalf Hoos",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "gandalfhoos@mail.com",
    image: "./images/pic_12.svg",
    initials: "GH",
  },
  {
    id: 13,
    name: "Gabriella",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "gabriella@mail.com",
    image: "./images/pic_13.svg",
    initials: "G",
  },
  {
    id: 14,
    name: "Hanny Shella",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "hannyshella@mail.com",
    image: "./images/pic_14.svg",
    initials: "HS",
  },
  {
    id: 15,
    name: "Ivankov",
    position: "Marketing Manager at Highspeed Studios",
    mobile: "+12 345 6789 0",
    email: "ivankov123@mail.com",
    image: "./images/pic_15.svg",
    initials: "I",
  },
];
