// mockEmployeeData.ts
export const employeeList = [
    {
      name: "Angela Moss",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "angelamoss@mail.com",
      initials: "AM",
    },
    {
      name: "Ahmad Zayn",
      position: "Photographer at Audio Video Teams",
      mobile: "+12 345 6789 0",
      email: "ahmadzayn@mail.com",
      initials: "AZ",
    },
    {
      name: "Brian Connor",
      position: "Designer at Crimson Guards Studios",
      mobile: "+12 345 6789 0",
      email: "brianconnor@mail.com",
      initials: "BC",
    },
    {
      name: "Courtney Hawkins",
      position: "Programmer at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "courtneyhawk@mail.com",
      initials: "CH",
    },
    {
      name: "Chyntia Smilee",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "angelamoss@mail.com",
      initials: "CS",
    },
    {
      name: "David Here",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "davidhere@mail.com",
      initials: "DH",
    },
    {
      name: "Dennise Lee",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "denniselee@mail.com",
      initials: "DL",
    },
    {
      name: "Erbatov Axie",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "erbatovaxie@mail.com",
      initials: "EA",
    },
    {
      name: "Evan Khan",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "angelamoss@mail.com",
      initials: "EK",
    },
    {
      name: "Fanny Humble",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "fannyhumble@mail.com",
      initials: "FH",
    },
    {
      name: "Franklin Jr.",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "franklinjr@mail.com",
      initials: "FJ",
    },
    {
      name: "Gandalf Hoos",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "gandalfhoos@mail.com",
      initials: "GH",
    },
    {
      name: "Gabriella",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "gabriella@mail.com",
      initials: "G",
    },
    {
      name: "Hanny Shella",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "hannyshella@mail.com",
      initials: "HS",
    },
    {
      name: "Ivankov",
      position: "Marketing Manager at Highspeed Studios",
      mobile: "+12 345 6789 0",
      email: "ivankov123@mail.com",
      initials: "I",
    },
  ];
  